name: deploy

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout release
      uses: actions/checkout@v3

    - name: install .env
      run: |
        echo "${{ secrets.DOT_ENV_DEFAULT }}" > $GITHUB_WORKSPACE/config/.env.default.env
        echo "${{ secrets.DOT_ENV_PRODUCT }}" > $GITHUB_WORKSPACE/config/.env.product.env

    - name: test
      run: echo "No Tests"
    
    - name: archive jgc_api
      run: tar cvfz $GITHUB_WORKSPACE/jgc_api.tar.gz *
      
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-2
        
    - name: upload to S3
      run: aws s3 cp --region us-east-2 $GITHUB_WORKSPACE/jgc_api.tar.gz s3://jgc-deploy
  
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name jgc
        --deployment-group-name jgc-api
        --file-exists-behavior OVERWRITE
        --s3-location bucket=jgc-deploy,bundleType=tgz,key=jgc_api.tar.gz
        --region us-east-2